
export const API = 'API'
export const API_REQUEST = 'API_REQUEST'
export const API_SUCCESS = 'API_SUCCESS'
export const API_ERROR = 'API_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'

export const PRODUCT_LISTING_SUCCESS = 'PRODUCT_LISTING_SUCCESS'
export const PRODUCT_LISTING_FAIL = 'PRODUCT_LISTING_FAIL'

export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS'
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL'

export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL'

export const PRODUCT_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'

export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'